name = "fightcred-web"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://fightcred-api-production.up.railway.app"
