name = "fightcred-web"
type = "javascript"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "fightcred-web-prod"
routes = [
  { pattern = "fightcred-web.pages.dev", zone_name = "pages.dev" }
]
