name = "fightcred-web"
type = "javascript"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "fightcred-web.pages.dev", zone_name = "pages.dev" }
]
